baseurl = "/"
languageCode = "en-us"
title = "Brian J. Connor"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[[menu.main]]
    name = "About Me"
    url = "/about_brian/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/bconnor17"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/brianjconnor"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/brianjconnor1/"
[[menu.main]]
    name = "Projects"
    url = "/my_projects/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

